import { useState, useEffect, useRef } from 'react'

export default function Step4Result({ state, html, history, onRefine, onBack, onCreateAnother }) {
  const [viewingHtml, setViewingHtml] = useState(html)
  const [refinementText, setRefinementText] = useState('')
  const [isRefining, setIsRefining] = useState(false)
  const [showCode, setShowCode] = useState(false)
  const [copied, setCopied] = useState(false)
  const chatEndRef = useRef(null)

  useEffect(() => { setViewingHtml(html) }, [html])
  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [history])

  async function handleRefineSubmit() {
    if (!refinementText.trim() || isRefining) return
    const text = refinementText.trim()
    setRefinementText('')
    setIsRefining(true)
    try {
      await onRefine(text)
    } catch (err) {
      alert('Error: ' + err.message)
    } finally {
      setIsRefining(false)
    }
  }

  function handleKeyDown(e) {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      handleRefineSubmit()
    }
  }

  function handleCopy() {
    navigator.clipboard.writeText(html)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  function handleDownloadHtml() {
    const blob = new Blob([html], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'widget.html'
    a.click()
    URL.revokeObjectURL(url)
  }

  function handleExport() {
    const escapedHtml = html.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$')

    const scriptableCode = `// ─────────────────────────────────────────────
// Scriptable Widget — generated by Widget Builder
// ─────────────────────────────────────────────

let html = \`${escapedHtml}\`

let wv = new WebView()
await wv.loadHTML(html, "")

let widget = new ListWidget()
widget.backgroundImage = await wv.getSnapshot()
widget.setPadding(0, 0, 0, 0)

Script.setWidget(widget)
Script.complete()`

    const printDoc = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Widget Setup — Scriptable</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Helvetica Neue", sans-serif;
      color: #111;
      padding: 48px 56px;
      max-width: 760px;
      margin: 0 auto;
      font-size: 14px;
      line-height: 1.6;
    }
    .header { margin-bottom: 36px; border-bottom: 2px solid #111; padding-bottom: 20px; }
    .header h1 { font-size: 26px; font-weight: 700; letter-spacing: -0.02em; margin-bottom: 6px; }
    .header p { color: #555; font-size: 13px; }
    h2 { font-size: 15px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.08em; margin-bottom: 14px; margin-top: 32px; color: #111; }
    .step-list { list-style: none; counter-reset: steps; }
    .step-list li {
      counter-increment: steps;
      display: flex;
      gap: 14px;
      margin-bottom: 12px;
      align-items: flex-start;
    }
    .step-list li::before {
      content: counter(steps);
      min-width: 24px;
      height: 24px;
      border-radius: 50%;
      background: #111;
      color: #fff;
      font-size: 11px;
      font-weight: 700;
      display: flex;
      align-items: center;
      justify-content: center;
      flex-shrink: 0;
      margin-top: 1px;
    }
    .app-store-note {
      background: #f4f4f4;
      border-radius: 8px;
      padding: 12px 16px;
      font-size: 13px;
      margin-bottom: 24px;
      color: #333;
    }
    .app-store-note strong { color: #111; }
    .code-block {
      background: #f6f6f6;
      border: 1px solid #ddd;
      border-radius: 8px;
      padding: 20px;
      font-family: "SF Mono", Menlo, "Courier New", monospace;
      font-size: 11px;
      line-height: 1.6;
      white-space: pre-wrap;
      word-break: break-all;
      page-break-inside: avoid;
      margin-top: 8px;
    }
    .tip {
      border-left: 3px solid #111;
      padding: 10px 14px;
      background: #fafafa;
      font-size: 13px;
      color: #444;
      margin-top: 24px;
      border-radius: 0 6px 6px 0;
    }
    @media print {
      body { padding: 32px 40px; }
      .code-block { font-size: 10px; }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>Getting your widget onto your phone</h1>
    <p>Follow these steps to add your generated widget to your iPhone or iPad home screen using Scriptable.</p>
  </div>

  <h2>Step 1 — Get Scriptable</h2>
  <div class="app-store-note">
    <strong>Scriptable</strong> is a free iOS app that lets you run JavaScript on your device and create custom home screen widgets.<br/>
    Search <strong>"Scriptable"</strong> on the App Store, or visit <strong>scriptable.app</strong>
  </div>

  <h2>Step 2 — Add the script</h2>
  <ol class="step-list">
    <li>Open <strong>Scriptable</strong> on your iPhone or iPad.</li>
    <li>Tap the <strong>+</strong> button in the top-right corner to create a new script.</li>
    <li>Tap the script body and select <strong>Select All → Delete</strong> to clear any placeholder code.</li>
    <li>Copy the entire code block on the next page and paste it in.</li>
    <li>Tap the script name at the top and rename it to something memorable, e.g. <strong>"My Widget"</strong>.</li>
    <li>Tap <strong>Done</strong>, then tap the <strong>▶ Run</strong> button once to verify it works — you should see a preview.</li>
  </ol>

  <h2>Step 3 — Add to home screen</h2>
  <ol class="step-list">
    <li>Go to your iPhone home screen and long-press until widgets jiggle.</li>
    <li>Tap the <strong>+</strong> button in the top-left corner.</li>
    <li>Search for <strong>Scriptable</strong> and choose a widget size.</li>
    <li>Tap <strong>Add Widget</strong>, then long-press the new widget and tap <strong>Edit Widget</strong>.</li>
    <li>Under <strong>Script</strong>, select <strong>"My Widget"</strong> (or whatever you named it).</li>
    <li>Tap anywhere to save. Your widget is live!</li>
  </ol>

  <div class="tip">
    <strong>Tip:</strong> If the widget shows a placeholder after adding it, wait a few seconds or open Scriptable and run the script once more.
  </div>

  <h2 style="margin-top:40px;">Your Scriptable code</h2>
  <p style="font-size:13px;color:#555;margin-bottom:8px;">Copy and paste this entire block into your Scriptable script.</p>
  <div class="code-block">${scriptableCode.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</div>
</body>
</html>`

    const win = window.open('', '_blank')
    win.document.write(printDoc)
    win.document.close()
    win.focus()
    setTimeout(() => win.print(), 400)
  }

  return (
    <div id="step4">
      <div className="result-title">Your Generated Widget</div>

      <div className="widget-preview-container">
        <iframe
          srcDoc={viewingHtml}
          sandbox="allow-scripts allow-same-origin"
          title="Widget Preview"
          className="widget-iframe"
        />
      </div>

      {/* Iteration chat panel */}
      <div className="chat-panel">
        <div className="chat-history">
          {history.map((entry, i) => (
            <div key={i} className="chat-entry">
              <div className="chat-bubble">
                <span className="chat-version">v{i + 1}</span>
                {entry.label}
              </div>
              {i < history.length - 1 && (
                <button
                  className="view-version-btn"
                  onClick={() => setViewingHtml(entry.html)}
                >
                  view
                </button>
              )}
            </div>
          ))}
          {isRefining && (
            <div className="chat-entry">
              <div className="chat-bubble chat-bubble--loading">Generating...</div>
            </div>
          )}
          <div ref={chatEndRef} />
        </div>
        <div className="chat-input-row">
          <input
            className="chat-input"
            type="text"
            placeholder="Request a change… (e.g. make it dark mode)"
            value={refinementText}
            onChange={e => setRefinementText(e.target.value)}
            onKeyDown={handleKeyDown}
            disabled={isRefining}
          />
          <button
            className="chat-send-btn"
            onClick={handleRefineSubmit}
            disabled={!refinementText.trim() || isRefining}
          >
            ↑
          </button>
        </div>
      </div>

      {/* Export */}
      <div className="export-section">
        <button className="export-phone-btn" onClick={handleExport}>
          Export to phone
        </button>
        <button
          className="export-code-toggle"
          onClick={() => setShowCode(v => !v)}
        >
          {showCode ? '▾ Hide code' : '▸ Show code'}
        </button>

        {showCode && (
          <div className="export-panel">
            <div className="export-code-header">
              <span>widget.html</span>
              <div className="export-code-actions">
                <button className="copy-btn" onClick={handleCopy}>
                  {copied ? '✓ Copied' : 'Copy'}
                </button>
                <button className="copy-btn" onClick={handleDownloadHtml}>
                  ↓ Download
                </button>
              </div>
            </div>
            <pre className="export-code"><code>{html}</code></pre>
          </div>
        )}
      </div>

      <div className="step-nav">
        <button className="back-btn" onClick={onBack}>← Back</button>
        <button className="create-another" onClick={onCreateAnother}>
          Create Another Widget
        </button>
      </div>
    </div>
  )
}
